var firstCategory = [
	{"id": 1, "question": "This is a question", "correct-answer": "correct", "option-2":"wrong answer 1", "option-3":"wrong answer 2", "option-4":"wrong answer 3", "explanation":"This is the explanation that goes with the question." },
	{"id": 2, "question": "This is a question", "correct-answer": "correct", "option-2":"wrong answer 1", "option-3":"wrong answer 2", "option-4":"wrong answer 3", "explanation":"This is the explanation that goes with the question." },
	{"id": 3, "question": "This is a question", "correct-answer": "correct", "option-2":"wrong answer 1", "option-3":"wrong answer 2", "option-4":"wrong answer 3", "explanation":"This is the explanation that goes with the question." },
	{"id": 4, "question": "This is a question", "correct-answer": "correct", "option-2":"wrong answer 1", "option-3":"wrong answer 2", "option-4":"wrong answer 3", "explanation":"This is the explanation that goes with the question." },
	{"id": 5, "question": "This is a question", "correct-answer": "correct", "option-2":"wrong answer 1", "option-3":"wrong answer 2", "option-4":"wrong answer 3", "explanation":"This is the explanation that goes with the question." },
	{"id": 6, "question": "This is a question", "correct-answer": "correct", "option-2":"wrong answer 1", "option-3":"wrong answer 2", "option-4":"wrong answer 3", "explanation":"This is the explanation that goes with the question." },
	{"id": 7, "question": "This is a question", "correct-answer": "correct", "option-2":"wrong answer 1", "option-3":"wrong answer 2", "option-4":"wrong answer 3", "explanation":"This is the explanation that goes with the question." },
	{"id": 8, "question": "This is a question", "correct-answer": "correct", "option-2":"wrong answer 1", "option-3":"wrong answer 2", "option-4":"wrong answer 3", "explanation":"This is the explanation that goes with the question." },
	{"id": 9, "question": "This is a question", "correct-answer": "correct", "option-2":"wrong answer 1", "option-3":"wrong answer 2", "option-4":"wrong answer 3", "explanation":"This is the explanation that goes with the question." },
	{"id": 10, "question": "This is a question", "correct-answer": "correct", "option-2":"wrong answer 1", "option-3":"wrong answer 2", "option-4":"wrong answer 3", "explanation":"This is the explanation that goes with the question." },
	{"id": 11, "question": "This is a question", "correct-answer": "correct", "option-2":"wrong answer 1", "option-3":"wrong answer 2", "option-4":"wrong answer 3", "explanation":"This is the explanation that goes with the question." },
	{"id": 12, "question": "This is a question", "correct-answer": "correct", "option-2":"wrong answer 1", "option-3":"wrong answer 2", "option-4":"wrong answer 3", "explanation":"This is the explanation that goes with the question." },
	{"id": 13, "question": "This is a question", "correct-answer": "correct", "option-2":"wrong answer 1", "option-3":"wrong answer 2", "option-4":"wrong answer 3", "explanation":"This is the explanation that goes with the question." },
	{"id": 14, "question": "This is a question", "correct-answer": "correct", "option-2":"wrong answer 1", "option-3":"wrong answer 2", "option-4":"wrong answer 3", "explanation":"This is the explanation that goes with the question." },
	{"id": 15, "question": "This is a question", "correct-answer": "correct", "option-2":"wrong answer 1", "option-3":"wrong answer 2", "option-4":"wrong answer 3", "explanation":"This is the explanation that goes with the question." }
];